language: python
python:
  - '2.7.12'

# safelist
branches:
  only:
    - staging

before_script:
  - pip3 install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pur_beurre_project.settings.travis

script:
  - pytest
